python -u intervention.py \
	--test_data_pth "data/math_nemotron_perturb_rand_small_test-rand100.json" \
	--output_pth "output/steer/math_nemotron_rand100_test_intervene_dir.json" \
	--intervention_vector "out_pt/nemotron-1d5b-amc-inconsistent-no-constrain-upper5-use_abs-dir-uf-ff.pt" \
  --reverse_intervention 0 \
  --model "nemotron" \
  --model_size "1.5b" \
  --left 0 \
  --right 500 \
  --layer_s 0 \
  --layer_e 29 \
  --coeff_select 1.0 \
  --max_token_generate 20 \
  --max_decode_step_while_intervene 1 \
  --record_probs 0 \
  --intervene_on_perturbed_step 1 \
  --include_final_answer_cue 1 \
  --step_key "perturb_step" \
  --context_key "context_text"
